use the_nexus::objects::{ObjectCategory::*, ObjectInfo};

pub fn get_object_info(id: u32) -> Option<ObjectInfo> {
    Some(match id {
        1720 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -11.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1837 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        503 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -5.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1735 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1869 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        419 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -2.5,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1731 => ObjectInfo {
            place_offset_x: -11.5,
            place_offset_y: -11.5,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1606 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        882 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1209 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        17 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -8.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1721 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -11.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        7 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Blocks,
        },
        695 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        1764 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1889 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        177 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1725 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -9.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1333 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1584 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        1891 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -6.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1741 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1846 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1848 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1602 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1757 => ObjectInfo {
            place_offset_x: -7.5,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1830 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1880 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1267 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1279 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1870 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        51 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1619 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        19 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 4.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        650 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        693 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        217 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -9.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        149 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1734 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1890 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -9.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        2 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Blocks,
        },
        479 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        931 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        97 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        408 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -12.5,
            tintable: true,
            solid: false,
            category: Deco,
        },
        6 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Blocks,
        },
        470 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        896 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        930 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1736 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1873 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1724 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Spikes,
        },
        476 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        935 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        18 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 4.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1266 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1280 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        869 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1605 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        929 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        697 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        468 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 14.25,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        1003 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1274 => ObjectInfo {
            place_offset_x: 5.0,
            place_offset_y: -5.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1879 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        478 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1620 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        227 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -4.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        916 => ObjectInfo {
            place_offset_x: -7.5,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Deco,
        },
        15 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 6.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1843 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1751 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1134 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1002 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        694 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        1767 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        137 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1813 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1603 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        721 => ObjectInfo {
            place_offset_x: -11.5,
            place_offset_y: -11.5,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1331 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        67 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -12.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        409 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        878 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        266 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        107 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 4.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1755 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        113 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 1.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1885 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        141 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        155 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        469 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        1583 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        138 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1740 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        939 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -6.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1281 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        150 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1715 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -12.5,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1618 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        678 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        480 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1247 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1054 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        87 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        888 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        1020 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1756 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1330 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        83 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Blocks,
        },
        472 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        660 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1729 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        928 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        186 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        471 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        106 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 18.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        649 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1730 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1859 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        223 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        917 => ObjectInfo {
            place_offset_x: -11.25,
            place_offset_y: -11.25,
            tintable: true,
            solid: false,
            category: Deco,
        },
        934 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1892 => ObjectInfo {
            place_offset_x: -7.5,
            place_offset_y: -9.75,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1607 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        183 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        395 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1717 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Spikes,
        },
        1596 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1001 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        216 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1004 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1845 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1876 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        5 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1709 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        458 => ObjectInfo {
            place_offset_x: -7.5,
            place_offset_y: -9.75,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        642 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1825 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        35 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -13.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1586 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        1600 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        10 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        20 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -2.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1697 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        1278 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1597 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        111 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        700 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        873 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 7.5,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1277 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1865 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        702 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        259 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1718 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Spikes,
        },
        874 => ObjectInfo {
            place_offset_x: -7.5,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1053 => ObjectInfo {
            place_offset_x: -7.5,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        659 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        157 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -1.5,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        154 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1050 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -2.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1834 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        909 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Deco,
        },
        881 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        45 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1884 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        211 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        132 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        494 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        222 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        477 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        907 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -4.5,
            tintable: true,
            solid: false,
            category: Deco,
        },
        242 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        696 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        1759 => ObjectInfo {
            place_offset_x: 10.5,
            place_offset_y: 9.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1765 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1059 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        46 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        158 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -1.5,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        218 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -6.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        722 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        933 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1202 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 13.5,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        505 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        136 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1135 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        159 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -1.5,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        115 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -5.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        641 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1601 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        86 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        139 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1051 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -2.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        883 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1137 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1847 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        895 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        474 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        919 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -10.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        1019 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        411 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1883 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        870 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1704 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1888 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        932 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        914 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1864 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        482 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1021 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1871 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        110 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 2.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        228 => ObjectInfo {
            place_offset_x: -7.5,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1723 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Spikes,
        },
        645 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        140 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -13.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1754 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        273 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1705 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1706 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1874 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        101 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        918 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        927 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1022 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1582 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        60 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        47 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1710 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        739 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        148 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1338 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        1832 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        85 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        745 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1753 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Blocks,
        },
        1833 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        84 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1058 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        143 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        1700 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        1519 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        53 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1862 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        871 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1273 => ObjectInfo {
            place_offset_x: 5.0,
            place_offset_y: -5.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        719 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1863 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1060 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        54 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        413 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1707 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1698 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        473 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        1831 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        185 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1205 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        1133 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1861 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1728 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1867 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        680 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        648 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1052 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -2.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1699 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Utilities,
        },
        396 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        48 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 2.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        1332 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -12.5,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        701 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        179 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -6.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        16 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -1.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1708 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        938 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        644 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1339 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        188 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        679 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1835 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1872 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1881 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        647 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        224 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        646 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        114 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -2.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        52 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        937 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        414 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -9.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1829 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        133 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        481 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        36 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1722 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -11.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1868 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        504 => ObjectInfo {
            place_offset_x: 5.0,
            place_offset_y: -5.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        734 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        12 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        49 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -2.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        187 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        41 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 20.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1203 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        135 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -11.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1758 => ObjectInfo {
            place_offset_x: -7.25,
            place_offset_y: 7.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        412 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1005 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        908 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -7.5,
            tintable: true,
            solid: false,
            category: Deco,
        },
        184 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1206 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        1207 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        699 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        698 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        21 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -8.0,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        394 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1866 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1875 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        460 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        1844 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1877 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        13 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        643 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        1204 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        99 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        1210 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        880 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        156 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Saws,
        },
        1766 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        890 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        889 => ObjectInfo {
            place_offset_x: 15.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        877 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Slopes,
        },
        658 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        3 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Blocks,
        },
        420 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -2.5,
            tintable: true,
            solid: false,
            category: GroundDeco,
        },
        410 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1768 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        11 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: false,
            solid: false,
            category: Utilities,
        },
        406 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -8.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        178 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: -8.0,
            tintable: true,
            solid: false,
            category: Spikes,
        },
        1604 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1136 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Deco,
        },
        1878 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        467 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Outlines,
        },
        50 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Pulsing,
        },
        4 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: true,
            category: Blocks,
        },
        1882 => ObjectInfo {
            place_offset_x: 0.0,
            place_offset_y: 0.0,
            tintable: true,
            solid: false,
            category: Blocks,
        },
        _ => return None,
    })
}
