use std::collections::{BTreeMap, HashMap};

use indexmap::IndexMap;

use wasm_bindgen::prelude::*;

use crate::util::{now, Rect};

use super::{
    layer::{ZLayer, ZLayerMap, Z_LAYERS},
    object::GDObject,
};

/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
pub const CHUNK_SIZE_BLOCKS: u32 = 20;
pub const CHUNK_SIZE_UNITS: u32 = CHUNK_SIZE_BLOCKS * 30;

/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED
pub const LEVEL_WIDTH_BLOCKS: u32 = 800;
pub const LEVEL_HEIGHT_BLOCKS: u32 = 800;
pub const LEVEL_WIDTH_UNITS: u32 = LEVEL_WIDTH_BLOCKS * 30;
pub const LEVEL_HEIGHT_UNITS: u32 = LEVEL_HEIGHT_BLOCKS * 30;

pub const LEVEL_RECT_BLOCKS: Rect<i32> =
    Rect::new(0, 0, LEVEL_WIDTH_BLOCKS as i32, LEVEL_HEIGHT_BLOCKS as i32);
pub const LEVEL_RECT_UNITS: Rect<i32> =
    Rect::new(0, 0, LEVEL_WIDTH_UNITS as i32, LEVEL_HEIGHT_UNITS as i32);

pub const END_POS_X: u32 = LEVEL_WIDTH_UNITS - 75;
pub const END_POS_Y: u32 = LEVEL_HEIGHT_UNITS - 75;
pub const END_RADIUS: u32 = 8 * 30;
