import { initializeApp } from "firebase-admin/app";

export { deleteObject, placeObject } from "./object";
export {
    initUserWithUsername,
    reportUser,
    reportedUserOperation,
    banUser,
    // clearReports,
} from "./user";

export {
    onKofiDonation,
    submitKofiTxId,
    changeNameGradient,
} from "./donations";

// TODO: add our uids
export const DEV_UIDS: string[] = [];

/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
export const CHUNK_SIZE_BLOCKS = 20;
export const CHUNK_SIZE_UNITS = CHUNK_SIZE_BLOCKS * 30;

/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
/// MAKE SURE YOU CHCNAGE THIS WHEVERRE  IT IS USED (THERE ARE ANOTHER PLACEIN WASM)
export const LEVEL_WIDTH_BLOCKS = 400;
export const LEVEL_HEIGHT_BLOCKS = 80;
export const LEVEL_WIDTH_UNITS = LEVEL_WIDTH_BLOCKS * 30;
export const LEVEL_HEIGHT_UNITS = LEVEL_HEIGHT_BLOCKS * 30;

initializeApp();
