<script lang="ts">
    import FadedScroll from "./components/FadedScroll.svelte";
    import Button from "./components/Button.svelte";
    import { analytics } from "./stores";

    let hasScrolledToBottom = false;

    let modal: HTMLDialogElement;

    let hidePopup = $analytics != null ? true : false;
</script>

{#if !hidePopup}
    <div
        class="absolute bottom-0 z-50 w-1/2 h-auto p-4 transform -translate-x-1/2 xs:w-full left-1/2"
    >
        <div
            class="flex-col w-full gap-3 p-3 text-center text-white rounded-lg shadow-lg sm:text-sm sm:w-full flex-center bg-menu-gray/90 shadow-black/40 backdrop-blur-md"
        >
            <p>
                <strong>
                    This site uses analytics to collect data about the event.
                    Please read our privacy policy below.
                </strong>
            </p>
            <Button
                type="white"
                class="p-2 w-max"
                aria-label="Read More"
                on:click={() => {
                    modal.showModal();
                }}
            >
                Read More
            </Button>
        </div>
    </div>
{/if}

<dialog
    aria-label="Privacy Policy Modal"
    class="dialog-panel menu-panel xs:w-80 xs:h-96 w-[600px] sm:w-[450px]"
    bind:this={modal}
>
    <FadedScroll bind:reachedBottom={hasScrolledToBottom}>
        <section>
            <h1><u><strong>Privacy Policy for GD Place</strong></u></h1>

            <h2>Definitions</h2>

            <p>For the purposes of this Privacy Policy:</p>

            <ul class="bulleted-list">
                <li>
                    <i>We</i> (referred to as either "We", "Us" or "Our") refers
                    to GD Place.
                </li>
                <li>
                    <i>Personal Data</i> is any information that relates to an identified
                    or identifiable individual.
                </li>
                <li>
                    <i>Service</i> refers to the Website.
                </li>
                <li>
                    <i>Usage Data</i> refers to data collected automatically, either
                    generated by the use of the Service or from the Service infrastructure
                    itself (for example, the duration of a page visit).
                </li>
                <li>
                    <i>You</i> means the individual accessing or using the Service.
                </li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>

            <p>
                We collect minimal Usage Data automatically while You are using
                the Service.
            </p>

            <h3>Analytics</h3>

            <h4>
                Cloudflare Web Analytics (<a
                    class="underline hover:decoration-dashed"
                    href="https://developers.cloudflare.com/analytics/web-analytics/understanding-web-analytics/dimensions/"
                    >Dimensions</a
                >,
                <a
                    class="underline hover:decoration-dashed"
                    href="https://developers.cloudflare.com/analytics/web-analytics/understanding-web-analytics/high-level-metrics/"
                    >High-level metrics</a
                >)
            </h4>

            <ul class="bulleted-list">
                <li>Country</li>
                <li>
                    Host (the domain, so <code>.gd</code>)
                </li>
                <li>
                    Path (different links You visit, so none for this event)
                </li>
                <li>Referer (how You found Our site)</li>
                <li>Device Type</li>
                <li>Browser</li>
                <li>Operating System</li>
                <li>Site (<code>place.gd</code>)</li>
                <li>
                    Visits (a page view originating from a different website)
                </li>
                <li>Page Views</li>
                <li>Page Load Time</li>
                <li>
                    Core Web Vitals (data about the site to understand the user
                    experience better)
                </li>
            </ul>

            <h3>Firebase Cloud Functions</h3>

            <ul class="bulleted-list">
                <li>
                    <p>
                        No Personal data or Usage data is stored by the Firebase
                        Cloud Function
                    </p>
                </li>
            </ul>

            <h3>Firebase Authentication</h3>

            <ul class="bulleted-list">
                <li>Email Address</li>
                <li>Username</li>
            </ul>

            <h2>Use of Your Personal Data and Usage Data</h2>
            <ul class="bulleted-list">
                <li>
                    To provide and maintain our Service, including to monitor
                    the usage of our Service.
                </li>
                <li>
                    To manage Your Account: The Personal Data You provide can
                    give You access to different functionalities of the Service
                    that are available to You as a registered user.
                </li>
                <li>
                    For other purposes: We may use your Usage data for purposes
                    such as data analysis for identifying usage trends.
                </li>
            </ul>

            <p>
                We use Cloudflare Turnstile to enhance the security of Our
                Service. Cloudflare Turnstile does not store cookies or
                personally identifiable information and is designed to protect
                against spam and abuse. For more details about Cloudflare
                Turnstile and its privacy practices, you can refer to
                Cloudflare's own privacy policy.
            </p>

            <b>No Personal data or Usage data is held in the form of Cookies.</b
            >
            <br /><br />
            <b
                >We will never share your Personal Data with any third-party
                companies or services. This excludes the required third-party
                companies that Our Services uses to provide You with a method of
                creating an account and loggin in.</b
            >

            <h2>Retention of Deletion of Your Personal Data</h2>

            <p>
                We reserve the right to retain Personal Data only for as long as
                is necessary for the purposes set out in this Privacy Policy.
                Our Service will give You the ability to delete certain
                information about You from within the Service. This information
                includes:
            </p>

            <ul class="bulleted-list">
                <li>Account Information.</li>
            </ul>

            <p>This information <b>does not</b> include:</p>

            <ul class="bulleted-list">
                <li>Objects placed or deleted by You.</li>
            </ul>

            <h2>Contact Us</h2>

            <p>
                If you have any questions about this Privacy Policy, You can
                contact us:
            </p>

            <ul class="bulleted-list">
                <li>
                    By email: <span class="select-text"
                        >geometrydash.place@gmail.com</span
                    >
                </li>
            </ul>
            <br />
            <p>
                By clicking <span class="text-[#47ff47]">Continue</span>, You
                accept how We collect and analyse Usage Data.
                <b>Cloudflare Web Analytics will continue to be enabled.</b>
            </p>
            <br />
            <p>
                By clicking <span class="text-[#ff4747]">Disable Analytics</span
                >, You do not agree to the collection of Usage Data.
                <b>Cloudflare Web Analytics will be disabled</b>.
            </p>
        </section>
    </FadedScroll>
    <div class="flex w-full gap-4">
        <Button
            type="decline"
            class="w-full"
            disabled={!hasScrolledToBottom}
            on:click={() => {
                modal.close();
                hidePopup = true;
                $analytics = true;
            }}
        >
            <p class="xs:text-sm">Disable Analytics</p>
        </Button>
        <Button
            type="accept"
            class="w-full"
            disabled={!hasScrolledToBottom}
            on:click={() => {
                modal.close();
                hidePopup = true;
                $analytics = false;
            }}
        >
            <p class="xs:text-sm">Continue</p>
        </Button>
    </div>
</dialog>
